apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  selector:
    app: {{ template "api.apiName" . }}
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.api.serviceType }}
