apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "api.apiName" . }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ template "api.apiName" . }}
  template:
    metadata:
      labels:
        app: {{ template "api.apiName" . }}
    spec:
      containers:
      - name: api
        image: {{ .Values.api.image }}
        resources:
          requests:
            memory: "32Mi"
            cpu: "500m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ template "api.apiName" . }}-configmap
        - secretRef:
            name: {{ template "api.apiName" . }}-secret
        # env:
        #   - name: Mongo__User
        #     valueFrom:
        #       secretKeyRef:
        #         key: MONGO_INITDB_ROOT_USERNAME
        #         {{- if empty .Values.mongodb.existSecret }}
        #         name: {{ .Release.Name }}-mongodb-secret
        #         {{- else }}
        #         name: {{ .Values.mongodb.existSecret }}
        #         {{- end }}
        #   - name: Mongo__Password
        #     valueFrom:
        #       secretKeyRef:
        #         key: MONGO_INITDB_ROOT_PASSWORD
        #         {{- if empty .Values.mongodb.existSecret }}
        #         name: {{ .Release.Name }}-mongodb-secret
        #         {{- else }}
        #         name: {{ .Values.mongodb.existSecret }}
        #         {{- end }}
